version: '3'
services:

  app:
    build: .
    depends_on:
      - statsd

  statsd:
    image: graphiteapp/graphite-statsd:latest
    ports:
      - "80:80"  # Reverse proxy to graphite dashboard.
      #- "8125:8125/udp"  # statsd.
